import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { RootCauseEngine } from '../engine/RootCauseEngine';
import { 
  CheckCircle2, AlertTriangle, ShieldCheck, Sprout, CloudRain, Activity, 
  Droplets, Thermometer, Bug, ArrowRight, FileText, Download, RotateCcw
} from 'lucide-react';

export default function EngineCompute() {
  const navigate = useNavigate();
  const [computing, setComputing] = useState(true);
  const [results, setResults] = useState(null);
  const [payload, setPayload] = useState(null);

  const [errorMsg, setErrorMsg] = useState(null);

  useEffect(() => {
    // 1. Load data from localStorage (Aggregated across Steps 1 to 4)
    const storedData = localStorage.getItem('agripulse_diagnostic');
    if (!storedData) {
      alert("No diagnostic data found. Please start from Step 1.");
      navigate('/reports');
      return;
    }

    const parsedData = JSON.parse(storedData);
    setPayload(parsedData);

    // 2. Initialize Engine & Simulate Processing Time
    try {
      const engine = new RootCauseEngine(parsedData);
      
      setTimeout(() => {
        try {
          const finalReport = engine.compute();
          setResults(finalReport);
          setComputing(false);
        } catch (err) {
          console.error(err);
          setErrorMsg(err.message || String(err));
          setComputing(false);
        }
      }, 2500); // 2.5s for dramatic effect
    } catch (err) {
      console.error(err);
      setErrorMsg(err.message || String(err));
      setComputing(false);
    }
  }, [navigate]);

  const resetFlow = () => {
    localStorage.removeItem('agripulse_diagnostic');
    navigate('/reports');
  };

  if (computing) {
    return (
      <div className="max-w-4xl mx-auto min-h-[60vh] flex flex-col items-center justify-center p-6 text-center">
        <div className="w-24 h-24 relative mb-8">
          <div className="absolute inset-0 border-4 border-indigo-200 rounded-full"></div>
          <div className="absolute inset-0 border-4 border-indigo-600 rounded-full border-t-transparent animate-spin"></div>
          <div className="absolute inset-0 flex items-center justify-center">
            <Activity className="text-indigo-600 animate-pulse" size={32} />
          </div>
        </div>
        <h2 className="text-3xl font-bold text-slate-800 mb-4 animate-pulse">Running Root Cause Engine...</h2>
        <div className="flex flex-col gap-3 text-slate-500 max-w-md mx-auto text-sm font-medium">
          <div className="flex items-center justify-between">
            <span>Analyzing Crop History...</span> <CheckCircle2 className="text-emerald-500" size={16}/>
          </div>
          <div className="flex items-center justify-between">
            <span>Cross-referencing 30-Day Weather...</span> <CheckCircle2 className="text-emerald-500" size={16}/>
          </div>
          <div className="flex items-center justify-between">
            <span>Checking IoT Soil Moisture & pH...</span> <CheckCircle2 className="text-emerald-500" size={16}/>
          </div>
          <div className="flex items-center justify-between opacity-50 animate-pulse">
            <span>Synthesizing Multi-Model AI Vision...</span> <Activity size={16}/>
          </div>
        </div>
      </div>
    );
  }

  if (errorMsg) {
    return (
      <div className="max-w-4xl mx-auto mt-20 p-8 bg-red-50 border-2 border-red-200 rounded-3xl text-center">
        <AlertTriangle className="mx-auto text-red-500 mb-4" size={48} />
        <h2 className="text-2xl font-bold text-red-800 mb-2">Engine Crashed</h2>
        <p className="text-red-600 mb-6">{errorMsg}</p>
        <button onClick={resetFlow} className="px-6 py-2 bg-red-600 text-white rounded-lg font-bold">Start Over</button>
      </div>
    );
  }

  if (!results) return null;

  const topIssue = results.topIssues.length > 0 ? results.topIssues[0] : null;

  return (
    <div className="max-w-6xl mx-auto space-y-8 pb-20 animate-in fade-in zoom-in-95 duration-500">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row items-center justify-between gap-4 border-b border-slate-200 pb-6">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="bg-emerald-100 text-emerald-700 text-xs font-bold px-2 py-1 rounded-full uppercase tracking-wider">Analysis Complete</span>
          </div>
          <h1 className="text-3xl font-bold text-slate-800">Final Diagnostic Report</h1>
          <p className="text-slate-500">Generated by AgriPulse Root Cause Engine</p>
        </div>
        <div className="flex gap-3">
          <button className="flex items-center gap-2 px-4 py-2 border border-slate-300 rounded-lg text-slate-600 hover:bg-slate-50 transition-colors font-medium text-sm">
            <Download size={16} /> PDF Report
          </button>
          <button onClick={resetFlow} className="flex items-center gap-2 px-4 py-2 bg-indigo-50 text-indigo-700 rounded-lg hover:bg-indigo-100 transition-colors font-medium text-sm">
            <RotateCcw size={16} /> New Diagnosis
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Column: Final Verdict */}
        <div className="lg:col-span-2 space-y-6">
          
          {topIssue ? (
            <div className={`rounded-3xl p-8 border-2 shadow-xl relative overflow-hidden ${topIssue.isCritical ? 'bg-red-50 border-red-200' : 'bg-orange-50 border-orange-200'}`}>
              <div className="absolute -right-10 -top-10 opacity-10">
                <AlertTriangle size={200} />
              </div>
              <div className="relative z-10">
                <div className="flex items-center gap-3 mb-4">
                  <div className={`p-2 rounded-xl ${topIssue.isCritical ? 'bg-red-100 text-red-600' : 'bg-orange-100 text-orange-600'}`}>
                    <AlertTriangle size={24} />
                  </div>
                  <span className={`font-bold tracking-wider uppercase text-sm ${topIssue.isCritical ? 'text-red-700' : 'text-orange-700'}`}>
                    Primary Root Cause Detected
                  </span>
                </div>
                
                <h2 className={`text-4xl font-extrabold mb-2 ${topIssue.isCritical ? 'text-red-900' : 'text-orange-900'}`}>
                  {topIssue.diagnosis}
                </h2>
                
                <div className="flex items-center gap-4 mt-6">
                  <div className="w-full bg-white/50 rounded-full h-4 overflow-hidden border border-white/60">
                    <div 
                      className={`h-full rounded-full transition-all duration-1000 ${topIssue.isCritical ? 'bg-red-500' : 'bg-orange-500'}`}
                      style={{ width: `${topIssue.probability}%` }}
                    ></div>
                  </div>
                  <span className={`text-2xl font-black ${topIssue.isCritical ? 'text-red-700' : 'text-orange-700'}`}>
                    {topIssue.probability}%
                  </span>
                </div>
                
                <div className="mt-8 bg-white/60 backdrop-blur-sm rounded-2xl p-6 border border-white/50">
                  <h4 className="font-bold text-slate-800 mb-4 flex items-center gap-2">
                    <FileText size={18} /> Evidence Trail (Why?)
                  </h4>
                  <ul className="space-y-3">
                    {topIssue.evidence.map((ev, idx) => (
                      <li key={idx} className="flex items-start gap-3 text-slate-700">
                        <CheckCircle2 className={`shrink-0 mt-0.5 ${topIssue.isCritical ? 'text-red-500' : 'text-orange-500'}`} size={18} />
                        <span className="font-medium">{ev}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          ) : (
            <div className="rounded-3xl p-8 border-2 border-emerald-200 bg-emerald-50 shadow-xl relative overflow-hidden">
              <div className="absolute -right-10 -top-10 opacity-10">
                <ShieldCheck size={200} />
              </div>
              <div className="relative z-10 text-center py-10">
                <div className="w-20 h-20 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-6">
                  <ShieldCheck size={40} />
                </div>
                <h2 className="text-3xl font-extrabold text-emerald-900 mb-2">Crop is Healthy!</h2>
                <p className="text-emerald-700 text-lg">No critical issues detected based on current data.</p>
              </div>
            </div>
          )}

          {/* Secondary Issues */}
          {results.topIssues.length > 1 && (
            <div className="bg-white rounded-3xl p-6 border border-slate-200 shadow-sm">
              <h3 className="font-bold text-slate-800 mb-4 text-lg">Secondary Factors to Watch</h3>
              <div className="space-y-4">
                {results.topIssues.slice(1).map((issue, idx) => (
                  <div key={idx} className="flex items-center justify-between p-4 bg-slate-50 rounded-xl border border-slate-100">
                    <div>
                      <h4 className="font-bold text-slate-700">{issue.diagnosis}</h4>
                      <p className="text-sm text-slate-500">{issue.evidence[0]}</p>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="w-24 bg-slate-200 rounded-full h-2 overflow-hidden">
                        <div className="bg-slate-400 h-full" style={{ width: `${issue.probability}%`}}></div>
                      </div>
                      <span className="font-bold text-slate-600 text-sm">{issue.probability}%</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

        </div>

        {/* Right Column: Data Summary */}
        <div className="space-y-6">
          <div className="bg-slate-900 text-slate-300 rounded-3xl p-6 shadow-xl">
            <h3 className="text-white font-bold text-lg mb-6 flex items-center gap-2 border-b border-slate-700 pb-4">
              <Activity size={20} className="text-indigo-400" /> Data Payload Summary
            </h3>
            
            <div className="space-y-6">
              <div>
                <div className="text-xs uppercase tracking-wider font-bold text-slate-500 mb-2">Weather (30 Days)</div>
                <div className="grid grid-cols-2 gap-2">
                  <div className="bg-slate-800 rounded-lg p-3 flex items-center gap-2">
                    <CloudRain className="text-blue-400" size={16}/> 
                    <span className="font-medium">{payload?.weather?.rain_sum || 0}mm</span>
                  </div>
                  <div className="bg-slate-800 rounded-lg p-3 flex items-center gap-2">
                    <Thermometer className="text-orange-400" size={16}/> 
                    <span className="font-medium">{payload?.weather?.temp_avg || 0}&deg;C</span>
                  </div>
                </div>
              </div>
              
              <div>
                <div className="text-xs uppercase tracking-wider font-bold text-slate-500 mb-2">IoT Sensors</div>
                <div className="grid grid-cols-2 gap-2">
                  <div className="bg-slate-800 rounded-lg p-3 flex items-center gap-3">
                    <Droplets className="text-cyan-400 shrink-0" size={16}/> 
                    <span className="font-medium text-sm">Moisture: {payload?.sensors?.moisture ?? 'N/A'}</span>
                  </div>
                  <div className="bg-slate-800 rounded-lg p-3 flex items-center gap-3">
                    <Activity className="text-pink-400 shrink-0" size={16}/> 
                    <span className="font-medium text-sm">pH: {payload?.sensors?.pH ?? 'N/A'}</span>
                  </div>
                  <div className="bg-slate-800 rounded-lg p-3 flex items-center gap-3 col-span-2">
                    <Sprout className="text-emerald-400 shrink-0" size={16}/> 
                    <span className="font-medium text-sm">N: {payload?.sensors?.nitrogen ?? 'N/A'} | P: {payload?.sensors?.phosphorus ?? 'N/A'} | K: {payload?.sensors?.potassium ?? 'N/A'}</span>
                  </div>
                </div>
              </div>

              <div>
                <div className="text-xs uppercase tracking-wider font-bold text-slate-500 mb-2">AI Vision</div>
                <div className="bg-slate-800 rounded-lg p-3 space-y-2">
                  <div className="flex items-center gap-2 text-sm">
                    <Activity className="text-emerald-400 shrink-0" size={14}/>
                    <span className="truncate">{payload?.vision?.[0]?.disease?.label || 'No Image Data'}</span>
                  </div>
                  <div className="flex items-center gap-2 text-sm">
                    <Bug className="text-purple-400 shrink-0" size={14}/>
                    <span className="truncate">{payload?.vision?.[0]?.pest?.label || 'No Pest Data'}</span>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
